Repository Braeden261/kendoSchool, pull requests merged in 2019-04, with the labels that each got.

#156 KG-54: Fixed visuals and logic for Sequence results on sequence_results page
  app.js
  public/MobilePages/Images/abdomen_text.png
  public/MobilePages/Images/head_text.png
  public/MobilePages/Images/leftarm_text.png
  public/MobilePages/Images/lefthand_text.png
  public/MobilePages/Images/leg_text.png
  public/MobilePages/Images/neck_text.png
  public/MobilePages/Images/rightarm_text.png
  public/MobilePages/Images/righthand_text.png
  public/MobilePages/Images/sequenceTargets.ai
  public/MobilePages/sequence_results.html
Labels: Dev, UX Work

#155 KG-76: Fixed percentage issue in VR environment
  public/student.html
Labels: Dev

#160 Deleted unused files and images from MobilePages folder
  public/MobilePages/Images/headseticon.png
  public/MobilePages/Images/leftleg_text.png
  public/MobilePages/Images/pelvis_text.png
  public/MobilePages/Images/ribcage_text.png
  public/MobilePages/Images/rightleg_text.png
  public/MobilePages/code.html
  public/MobilePages/connecting.html
  public/MobilePages/sequence_results.html
  public/MobilePages/start.html
Labels: Dev, Ready For Test

#162 KG-67: Waiting for Student gif
  public/MobilePages/waiting.html
  public/assets/images/waitingForStudentAnimation/Adobe After Effects Auto-Save/studentAnimation auto-save 1.aep
Labels: Dev

#163 KG-49: Disabled zooming functionality for Mobile pages and changed background colour of all pages
  public/MobilePages/performance.html
  public/MobilePages/sequence_results.html
  public/MobilePages/style.css
  public/MobilePages/waiting.html
  public/styles/index.css
Labels: Dev, Ready For Test

#165 KG-82: Fixed missing text bug for larger mobile displays
  public/MobilePages/waiting.html
Labels: Bug, Dev, Ready For Test, UX Work

#148 KG-73: Add Motion Reset on Physical Menu Items
  public/assets/images/waitingForStudentAnimation/studentAnimation.aep
  public/js/menu-component.js
  public/student-test.html
  public/student.html
Labels: Dev, Ready For Test

#169 KG-43: Update Mobile version of Kendo Gakko Logo
  public/MobilePages/performance.html
  public/MobilePages/sequence.html
  public/MobilePages/sequence_results.html
  public/MobilePages/waiting.html
  public/assets/lander-images/LanderPage_Concept.ai
  public/assets/lander-images/Title-Katanas-mobile.png
  public/index.html
  public/js/detect-device.js
Labels: Dev, UX Work

#171 KG-83: Updated 'Begin' Lantern physics to match other menu lanterns
  public/student.html
Labels: Dev

#167 KG-70: Dynamic Strike Sequence Display
  app.js
  public/MobilePages/sequence_results.html
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp18.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp19.aep
  public/assets/images/sequenceTargetAnimations/videos/Null.mp4
  public/js/event-manager-component.js
  public/student-test.html
  public/student.html
Labels: Dev

#180 KG-86: Begin lantern should drop after sequence is shown + msc fixes
  public/assets/images/sequenceTargetAnimations/SequenceTargets.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp20.aep
  public/assets/images/sequenceTargetAnimations/videos/RightArm(K)2.mp4
  public/js/event-manager-component.js
  public/js/menu-component.js
  public/student.html
Labels: Dev
