Repository Braeden261/kendoSchool, pull requests merged in 2019-03, with the labels that each got.

#86 KG-11
  public/assets/lander-images/Katanas.png
  public/assets/lander-images/LanderPage_Concept.ai
  public/assets/lander-images/LanderPage_Concept.png
  public/assets/lander-images/Master.png
  public/assets/lander-images/MasterInstruction-01.png
  public/assets/lander-images/MasterInstruction-02.png
  public/assets/lander-images/MasterInstruction-03.png
  public/assets/lander-images/Student.png
  public/assets/lander-images/StudentInstruction-01.png
  public/assets/lander-images/StudentInstruction-02.png
  public/assets/lander-images/StudentInstruction-03.png
  public/assets/lander-images/Title-Katanas.png
  public/assets/lander-images/Title.png
  public/index.html
  public/styles/index.css
Labels: Ready For Test

#89 KG-25_Edit: Mobile Lander Page Layout Updates
  public/assets/lander-images/LanderPage_Concept.ai
  public/assets/lander-images/MasterInstruction-03.png
  public/index.html
  public/js/detect-device.js
  public/styles/index.css
Labels: In Review

#88 KG-32: Updating Skydomes
  public/assets/textures/skyTexture/nightSky.png
  public/assets/textures/skyTexture/sky-01.png
  public/assets/textures/skyTexture/sky-02.png
  public/assets/textures/skyTexture/skyDome.ai
  public/student.html
Labels: Ready For Test

#91 KG-20: Create Training Dummy Model
  public/assets/models/objFiles/dummy/trainingDummy.obj
  public/assets/models/objFiles/sword/sword.mtl
  public/assets/models/objFiles/sword/swordTexture_v001.png
  public/assets/models/trainingDummy_Maya/Dummy_v001.ma
  public/assets/models/trainingDummy_Maya/Dummy_v002.ma
  public/assets/models/trainingDummy_Maya/Dummy_v005.ma
  public/assets/textures/dummyTexture/.mayaSwatches/dummyTexture.png_hcm.swatch
  public/assets/textures/dummyTexture/Dummy_v003.ma
  public/assets/textures/dummyTexture/Dummy_v004.ma
  public/assets/textures/dummyTexture/TexturePNG/dummyTexture.png
  public/assets/textures/dummyTexture/dummyTexture.psd
  public/assets/textures/dummyTexture/dummyUV.png
Labels: 3D Model, Ready For Test

#104 KG-31: Add Dummy and Sword Geometry into Environment
  public/assets/models/kendoSword_Maya/kendoSword_v006.ma
  public/assets/models/kendoSword_Maya/kendoSword_v007.ma
  public/assets/models/objFiles/sword/sword_v001.obj
  public/assets/models/objFiles/sword/sword_v002.obj
  public/assets/models/objFiles/sword/sword_v003.mtl
  public/assets/models/objFiles/sword/sword_v003.obj
  public/assets/textures/swordTexture/TexturePNG/.mayaSwatches/swordTexture_v001.png_hcm.swatch
  public/assets/textures/swordTexture/TexturePNG/swordTexture.png
  public/student.html
Labels: Dev, Ready For Test

#121 KG-37: Physical Menu in VR Environment - Technical Requirements
  package-lock.json
  public/MobilePages/sequence_results.html
  public/assets/models/objFiles/lantern/lantern_menu.obj
  public/js/menu-component.js
  public/student.html
Labels: Dev, Ready For Test

#134 KG-68: Sequence Target Animations - DR
  public/assets/images/sequenceTargetAnimations/Adobe After Effects Auto-Save/SequenceTargets auto-save 1.aep
  public/assets/images/sequenceTargetAnimations/Adobe After Effects Auto-Save/SequenceTargets auto-save 2.aep
  public/assets/images/sequenceTargetAnimations/Adobe After Effects Auto-Save/SequenceTargets auto-save 3.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets.aep
  public/assets/images/sequenceTargetAnimations/videos/Abdomen(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Abdomen(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Head(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Head(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftArm(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftArm(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftHand(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftHand(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Leg(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Leg(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Neck(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Neck(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightArm(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightArm(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightHand(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightHand(K).mp4
Labels: UX Work

#139 Add Physical Menu Lantern textures into environment
  public/student.html
Labels: Dev, Ready For Test

#144 KG-66: "Waiting For Student" Animation - DR
  public/assets/images/waitingForStudentAnimation/animationAssets_waitingForStudent.ai
  public/assets/images/waitingForStudentAnimation/studentAnimation.aep
  public/assets/images/waitingForStudentAnimation/waitingForStudent.gif
  public/assets/images/waitingForStudentAnimation/waitingForStudent.mp4
Labels: Ready For Test, UX Work

#136 KG-31: Implement Separated Dummy Hit Boxes - TR
  public/student.html
Labels: Dev, In Testing

#146 KG-68B: Updated sequence target animations and response graphics
  public/assets/images/responseGraphics/Response.aep
  public/assets/images/responseGraphics/Response_AME/tmpAEtoAMEProject-Comp 17.aep
  public/assets/images/responseGraphics/Response_AME/tmpAEtoAMEProject-Comp 18.aep
  public/assets/images/responseGraphics/videos/Great.mp4
  public/assets/images/responseGraphics/videos/Weak.mp4
  public/assets/images/sequenceTargetAnimations/Adobe After Effects Auto-Save/SequenceTargets auto-save 4.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp1.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp10.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp11.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp12.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp13.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp14.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp15.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp16.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp17.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp2.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp3.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp4.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp5.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp6.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp7.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp8.aep
  public/assets/images/sequenceTargetAnimations/SequenceTargets_AME/tmpAEtoAMEProject-FinalComp9.aep
  public/assets/images/sequenceTargetAnimations/videos/Abdomen(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Abdomen(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Head(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Head(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftArm(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftArm(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftHand(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/LeftHand(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Leg(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Leg(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/Neck(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/Neck(K).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightArm(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightHand(EK).mp4
  public/assets/images/sequenceTargetAnimations/videos/RightHand(K).mp4
Labels: Ready For Test, UX Work
